OS_Ass3:
	sudo gcc singleBowl-Mutex.c -o OneA -lpthread
	sudo gcc singleBowl-Semaphores.c -o OneB -lpthread
	sudo gcc twoBowls-Mutex.c -o OneC -lpthread
	sudo gcc twoBowls-Semaphores.c -o OneD -lpthread

