OS_Ass3:
	sudo gcc singleBowl-Mutex.c -o singleBowl-Mutex -lpthread
	sudo gcc singleBowl-Semaphores.c -o singleBowl-Semaphores -lpthread
	sudo gcc twoBowls-Mutex.c -o twoBowls-Mutex -lpthread
	sudo gcc twoBowls-Semaphores.c -o twoBowls-Semaphores -lpthread

